### ISSUE TITLE
New-CmAzCoreAlerts to set up alerts

### ISSUE THREAD

**Issue by nathankitchen** [Trustmarque/cloudmarque-azure-pwsh#198]
This work requires two new cmdlets:

**New-CmAzCoreLogAlerts**

- [ ] Investigate SLA time for log alerts and how delayed will they be in relation to their metric counterparts, highlight your findings in the settings file.
- [ ] Add the ability to deploy the same log alerts used in Cloudmarque.Extensions and make them configurable in the settings file using the format below (Map the "types" to the required KQL syntax in a separately defined yml file):

```yml
      component: "core.alerts"
      groups:     # Standard is to group alert settings in an area called "alerts"
      
      - name: "sqlstandard"
        alerts:
        - type: "minTransactionsPerSecond"
            parameters:
              threshold: 1000
              priority: 5         # Maps to the action group

      - name: "vmstandard"
        alerts:
        - type: "highCpu"
          description: ""  # Optional, try to default to something sensible if this isn't specified (?) TBC what is sensible
          parameters:
            threshold: 95
            priority: 1         # Maps to the action group
        - type: "lowDiskSpace"
          parameters:
            percentRemaining: 95
            diskSpaceRemainingGb: 10
            priority: 1
        - type: "lowDiskSpace" # note here that there are two lowDiskSpace entries
          parameters:
            percentRemaining: 90
            diskSpaceRemainingGb: 20
            priority: 2
        - type: "ramusage"
          parameters:
            percentRemaining: 90
            ramRemainingGb: 20
            priority: 2

```

- [ ] Add enabled flag for each alert.

**New-CmAzCoreMetricAlerts**

- [ ] Add ability to deploy the same alerts defined above but as metric alerts. 
- [ ] Pass Cm-Service values to determine what resources should have what alert groups.
- [ ] Try and configure the alerts using the same format as above, including the enabled flag.
- [ ] Investigate how often the same alert may be raised in a given time, do we need to configure "back-off" times to ensure users are not spammed with the same alerts.
