### ISSUE TITLE
New-CmAzIaasVm add support for availability zones

### ISSUE THREAD

**Issue by JBiasilloTM** [Trustmarque/cloudmarque-azure-pwsh#215]
Add support for availability zones in VMs the New-CmAzIaasVm cmdlet. In the [virtualmachines configuration section](https://docs.trustmarque.com/cloudmarque/reference/commands/new-cmaziaasvm.html) there should be an additional `zone` setting:

``` yaml
    virtualMachines:     # Mandatory
      - name: "string"    # Mandatory
        size: "string"    # Mandatory
        zone: 1         # Optional
        updateGroup: "Critical"    # Optional
        updateFrequency: "Monthly"    # Optional
```

The setting should be:
 - optional
 - numeric
 - ranged between 1 and 3
 - default to 1
 - example should be set to 1

Example: https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-simple-zones
