### ISSUE TITLE
New-CmAzIaasVm add support for availability sets

### ISSUE THREAD

**Issue by nathankitchen** [Trustmarque/cloudmarque-azure-pwsh#226]
Support for availability sets within the New-CmAzIaasVm cmdlet.

Example: https://github.com/Azure/azure-quickstart-templates/blob/master/201-vm-copy-index-loops/azuredeploy.json

Arm template ref: https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2018-10-01/availabilitysets

```yaml
availabilitySets:
- name: 
  location:
  sku:
    name:
    tier:                                            # Standard or Basic
    capacity:
  platformUpdateDomainCount: 
  platformFaultDomainCount:
  proximityPlacementGroup:
  service:
    publish:
      availabilitySet:
```
Add "AvailabilitySet" property to each vm settingsObject. the value should be whats passed into Get-CmAzResourceName to generate the availability set name.
