### ISSUE TITLE
New-CmAzIaasVm support for Defender/Antimalware extension

### ISSUE THREAD

**Issue by nathankitchen** [Trustmarque/cloudmarque-azure-pwsh#230]
Add the anti-malware extension to our VM provisioning ARM template/script. An example JSON can be found [as a quickstart here](https://github.com/Azure/azure-quickstart-templates/blob/master/anti-malware-extension-windows-vm/). In addition, [this blog post](https://charbelnemnom.com/how-to-update-microsoft-antimalware-policies-for-azure-virtual-machines-with-powershell-arm-json-azuresecurity/) has some useful context, while [this one](https://www.rdsgurus.com/azure-resource-manager-and-json-templates-to-deploy-rds-in-azure-iaas-part-8-defender-bginfo/) seems to show non-preview API versions being used.

Suggested settings file structure looks something like this (note this would sit in the objects within the `virtualmachines` array:

``` yaml
 - name: myVm
   size: DS3v2_16
   antimalware:
     enable: true
     realtime:
       enabled: true
       excludePaths:
       - "path1"
       - "path2"
       excludeExtensions:
       - ".mdf"
       - ".ldf"
       excludeProcesses:
       - "something.exe"
       - "somethingelse.exe"
     scheduled:
       enabled: true
       scanType": "Quick"
       day: 7
       time: 120
```
