### ISSUE TITLE
General - replace region with location in yml

### ISSUE THREAD

**Issue by deepend-dev** [Trustmarque/cloudmarque-azure-pwsh#294]
### Issue
We should use location instead of region across the codebase for consistency.

### Example

`functions.yml`

```yml

functionAppSolutions:
  - name: Paas-Test-Func-Rg1
    service:
      publish:
        resourceGroup:
    consumptionPlans:                                         # Consumption plan has predefined type - each fuction will have its own service plan.
      - name: Paas-Test-Func-Con1
        runtime: python|3.7                                   # Accepts in format: runtime|runtimeVersion
        kind: windows                                         # windows | linux
        region: uksouth
        enableAppInsight: true
        service:
          publish:
            function:
            appServicePlan:
          dependencies:
            storage:
```
