### ISSUE TITLE
Core - New-CmAzCustomExtension

### ISSUE THREAD

**Issue by nathankitchen** [Trustmarque/cloudmarque-azure-pwsh#321]
Add a new public CmdLet to enable generic deployment of an ARM template as a framework extension point. As with all other CmdLets, this would allow:

 - Self-loading deployments using the `component: "extension"` header value.
 - A library of reusable templates automatically resolved in a `[REPO]/_extensions` directory.
 - The ability to plug into useful functionality like the name generator and service locator.

The following proposed YAML structure would enable these capabilities:

``` yaml
component: extension

service:
  dependencies:
    keyvault: Core-Test-Kv
    workspace: Core-Test-Ws
  publish:
    resourceGroup: Core-Test-Auto-Rg
    automation: Core-Test-Auto

# This is an array of name parameters. Loop through it and for each entry call "Get-CmAzResourecName", saving each
# generated name value in an array.
names:
 - newVm:
     architecture: iaas
     resourcetype: vm
     region: uk
     name: test
     length: 32

templates:
 - name: something.json # by default, locate these in ./_extensions folder relative to the  CmAzContext project.
 - parameters:
    - key:
        type: static                   # Simply pass this parameter to the ARM deployment as whatever value is supplied.
        value: "Here is a parameter"  
    - key2:
        type: dependency               # Service locate the full resource name from the dependencies list and provide as a parameter.
        value: workspace
    - key3:
        type: name                     # Generate/pass the name from the name list (see names: section).
        value: newVm
```
