### ISSUE TITLE
New-CmAzSecurityPolicy

### ISSUE THREAD

**Issue by nathankitchen** [Trustmarque/cloudmarque-azure-pwsh#347]
Ability to deploy an ARM template containing custom policies.

https://docs.microsoft.com/en-us/azure/governance/policy/tutorials/create-and-manage
https://docs.microsoft.com/en-us/azure/governance/policy/tutorials/create-custom-policy-definition

PowerShell should review a `policy.yml` file with the following structure:

``` yaml
initiatives:
  - name: Cloudmarque Policies
    description: "Some example policies"
    category: "Governance"
    version: "1.0"
    definitions:
     - allowed-locations
    parameters:
     - name: "Region Name"
        value: "EU North"
     - name: "Banlist"
        value: "192.168.2.8"
```
This should be deployed with the cmdlet:

``` powershell
New-CmAzSecurityPolicy -SettingsFile "policy.yml" -DefinitionDirectory "./directory"
```
`DefinitionDirectory` parameter should be optional. If not provided, this should default to `_policy` in the project directory root.

The PowerShell cmdlet should loop through all values of definitions in each initiative and create a de-duplicated list of strings. These should correspond to filenames in the `DefinitionDirectory` directory, for example:

```
./_policy/allowed-locations.json
./_policy/allowed-locations.params.json
```

The cmdlet should loop through all the definitions and add them to the current subscription scope using:

``` powershell
New-AzPolicyDefinition -Name 'storageLocations' -Description 'Policy to specify locations for storage accounts.' -Policy $policy -Parameter $parameters
```

It should then loop through all initiatives and call:

``` powershell
New-AzPolicySetDefinition -Name 'VMPolicySetDefinition' -Metadata '{"category":"CATEGORYHERE"}' -PolicyDefinition 'def'
```

This provides a capability to create and deploy a range of standardised policy definitions and initiatives using a simple directory structure.
